ac_gradient_clip: 100
alpha: 0.2
batch_size: 128
actor_lr: 0.0003
critic_lr: 0.0003
gamma: 0.99
max_epochs_since_update_decay_interval: 150000.0

state_dim: 17
action_dim: 3
hidden_sizes: 256
max_action: 1

temperature_opt: False

tau: 0.005
update_interval: 2
expl_noise: 0.2

eval_episode: 10
eval_freq: 10000
start_steps: 5000
max_step: 1000000
tar_env_interact_freq: 10

gaussian_noise_std: 1.0

device: cuda

cql_max_target_backup: False
backup_entropy: True
cql_n_actions: 10
cql_importance_sample: True
cql_temp: 1.0
cql_clip_diff_min: -1000000
cql_clip_diff_max: 1000000
cql_lagrange: False
cql_alpha: 10.0
cql_target_action_gap: 1.0
n_state: 10


save_freq: 5000
